[general]
logging_enabled = true
logging_frequency = 1
output_path = ""

[features]
character_stats = true
skill_usage = true
item_logging = true
enemy_metrics = true
positioning = true
combat_metrics = true
environmental_factors = true
death_and_recovery = true
rewards_logging = true
resource_usage = true
external_buffs_debuffs = true

[advanced]
filter_by_enemy_type = []
filter_by_location = ""
preprocess_data = true
anonymize_data = true

[output]
format = "json"
pretty_print = true
